# Site settings
title: "Mattia Tupone resume"
description: "mattups - resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "Mattia Tupone"
resume_title: "DevOps Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email: "tupone.mattia@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "555-7334"
resume_contact_address: "742 Evergreen Terrace, Springfield"

resume_header_contact_info: "Lanciano (CH), Italy | tupone.mattia@gmail.com"
display_header_contact_info: "true"

resume_header_intro: "<p><i>Patterns before tools.</i><br><br>
  I'm a DevOps Engineer based in Italy with a strong passion for automation and operations.
  Self-motivated and quick learner with experience in Devops and Systems Engineering/Design area.
  <br><br>

  Constantly evolving to embrace the next challenge, give me a shell and I'll be happy with it.
  </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_recognition: true
# resume_section_links:           true
# resume_section_associations:    true
resume_section_interests: true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/mattups"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url: "https://www.linkedin.com/in/mattia-tupone-660450a6/"
  resume_instagram_url: "https://www.instagram.com/tups__/"
  #resume_website_url:           "https://mattups.github.io/resume/"
  resume_medium_url: "https://medium.com/@tupone.mattia"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
