# Site settings
title: "Nick Becker resume"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Nick Becker"
resume_title:                   "Senior Engineer, Collaboration"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "nick_the_engineer@atomictinker.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "410-541-6232"
resume_contact_address:         "4309 Samantha Dr, Raleigh, NC"

resume_header_contact_info:     "4309 Samantha Dr, Raleigh, NC • 410-541-6232 • nick_the_engineer@atomictinker.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Architect/engineer with 15+ years experience in network, collaboration and software development space. A strong problem solver recognized for dedication and attention to detail to complete project on time and deliver effective goal oriented results.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/nickbec10/resume"
  resume_twitter_url:           "http://twitter.com/nicbecker"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  resume_instagram_url:         "https://www.instagram.com/aeon_sumo/"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
